### ISSUE TITLE
Permalink is not being generated

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [fnando/permalink#7]
I'm creating a record from rails admin but the permalink field stays blank. Any idea what could be the issue here?

```ruby
class MyModal < ActiveRecord::Base
  validates :name, presence: true
  permalink :name, unique: true #, force: true
end
```

**Comment by fnando** [comment]
Did you ever discover what the issue? If not, can you create a project that reproduces the issue, so I can take a look?
